### ISSUE TITLE
Plugin loading "WARNING: DATA RACE"

### ISSUE THREAD

**Issue by ppalucki** [intelsdi-x/snap#922] opened 2016-05-13 14:13 UTC
I cannot assess the severity of this error, because probably it only happens, during tests with `-race`, but we are doing integration tests of our code, that also runs tests for snap plugin we wrote and by default we have `-race` flag turned on.

In production code, without `-race` the [code after](https://golang.org/src/os/exec/exec.go#L396) `process.Wait()`, is not run so the race doesn't occur.
- OS Version: **ubuntu 14.04**
- Snap version: **master/1d87e72**
- Environment: normal, **"go version go1.6 linux/amd64"**
- Steps to reproduce:
1. `cd plugin/collector/snap-collector-mock1`
2. replace `main_test.go` with (to have less verbose traceback)

``` go
package main

import (
    "testing"

    "github.com/intelsdi-x/snap/control"
    "github.com/intelsdi-x/snap/core"
)

func TestLoad(t *testing.T) {
    c := control.New(control.GetDefaultConfig())
    c.Start()

    rp, _ := core.NewRequestedPlugin("./snap-collector-mock1")

    _, err := c.Load(rp)
    if err != nil {
        panic(err)
    }
}
```

 3.`go build` to have /snap-collector-mock1
 4.`go test -race` returns with `WARNING: DATA RACE`

attached data race warning on accessing file descriptor.

From the tracebacks below you can see, problem is access to `.fd` in `struct File` who is used
by main goroutine in `Wait(`) method and from goroutines that scan over stdout, stderr to communicate with plugin and copy values to logs.

Explanation:
[`WaitForExit()`](https://github.com/intelsdi-x/snap/blob/1d87e72dfaa0f9555e6e7711a5e24cd1daedaf6d/control/plugin/execution.go#L95) tries to close descriptors (and set [`file.fd = -1`](https://golang.org/src/os/file_unix.go#L143)) after command ends, but in the meantime there are two goroutines that use this file descriptor to:
- read from [`waitForResponseFromPlugin()`](https://github.com/intelsdi-x/snap/blob/1d87e72dfaa0f9555e6e7711a5e24cd1daedaf6d/control/plugin/execution.go#L276)
- read from [`logStdErr()`](https://github.com/intelsdi-x/snap/blob/1d87e72dfaa0f9555e6e7711a5e24cd1daedaf6d/control/plugin/execution.go#L325)

They try to read a value of `fd` field here [file_unix.go:read()](https://golang.org/src/os/file_unix.go#L228), to do syscall `read()`.

~~Possible solution may be (not tested, just an idea) use of [Cmd.StdoutPipe](`https://golang.org/pkg/os/exec/#Cmd.StdoutPipe`) and pass to to goroutines that need to read over it - you cannot protect File with just simple mutex.~~ edited it is already [there ](https://github.com/intelsdi-x/snap/blob/master/control/plugin/execution.go#L120)

> Wait will close the pipe after seeing the command exit, so most callers need not close the pipe themselves; however, an implication is that it is incorrect to call Wait before all reads from the pipe have completed 

description of [StdoutPipe ](https://golang.org/pkg/os/exec/#Cmd.StdoutPipe)\- reads should end before calling `Wait()`
- Actual results

```
INFO[0000] control started                               _block=start _module=control
INFO[0000] plugin load called                            _block=load _module=control
INFO[0000] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-collector-mock1
PASS
INFO[0000] No previous pool found for loaded plugin      _block=subscribe-pool _module=control-runner event=Control.PluginLoaded plugin-name=mock plugin-type=collector plugin-version=1
==================
WARNING: DATA RACE
Write by goroutine 21:
  os.(*file).close()
      /home/ppalucki/src/go/src/os/file_unix.go:143 +0x1be
  os.(*File).Close()
      /home/ppalucki/src/go/src/os/file_unix.go:132 +0x88
  os/exec.(*Cmd).closeDescriptors()
      /home/ppalucki/src/go/src/os/exec/exec.go:245 +0x9f
  os/exec.(*Cmd).Wait()
      /home/ppalucki/src/go/src/os/exec/exec.go:406 +0x4c4
  github.com/intelsdi-x/snap/control/plugin.(*ExecutablePlugin).WaitForExit()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:96 +0x4b
  github.com/intelsdi-x/snap/control/plugin.waitForKilledPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:342 +0x52

Previous read by goroutine 19:
  os.(*File).read()
      /home/ppalucki/src/go/src/os/file_unix.go:228 +0x57
  os.(*File).Read()
      /home/ppalucki/src/go/src/os/file.go:95 +0xbc
  bufio.(*Scanner).Scan()
      /home/ppalucki/src/go/src/bufio/scan.go:208 +0x823
  github.com/intelsdi-x/snap/control/plugin.waitForResponseFromPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:286 +0x4a0

Goroutine 21 (running) created at:
  github.com/intelsdi-x/snap/control/plugin.waitHandling()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:195 +0x5c4
  github.com/intelsdi-x/snap/control/plugin.(*ExecutablePlugin).WaitForResponse()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:140 +0xbb
  github.com/intelsdi-x/snap/control.(*pluginManager).LoadPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin_manager.go:304 +0xe90
  github.com/intelsdi-x/snap/control.(*pluginControl).Load()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/control.go:286 +0x6b6
  github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1.TestLoad()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1/main_test.go:35 +0x7a
  testing.tRunner()
      /home/ppalucki/src/go/src/testing/testing.go:473 +0xdc

Goroutine 19 (finished) created at:
  github.com/intelsdi-x/snap/control/plugin.waitHandling()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:188 +0x407
  github.com/intelsdi-x/snap/control/plugin.(*ExecutablePlugin).WaitForResponse()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:140 +0xbb
  github.com/intelsdi-x/snap/control.(*pluginManager).LoadPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin_manager.go:304 +0xe90
  github.com/intelsdi-x/snap/control.(*pluginControl).Load()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/control.go:286 +0x6b6
  github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1.TestLoad()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1/main_test.go:35 +0x7a
  testing.tRunner()
      /home/ppalucki/src/go/src/testing/testing.go:473 +0xdc
==================
==================
WARNING: DATA RACE
Write by goroutine 21:
  os.(*file).close()
      /home/ppalucki/src/go/src/os/file_unix.go:143 +0x1be
  os.(*File).Close()
      /home/ppalucki/src/go/src/os/file_unix.go:132 +0x88
  os/exec.(*Cmd).closeDescriptors()
      /home/ppalucki/src/go/src/os/exec/exec.go:245 +0x9f
  os/exec.(*Cmd).Wait()
      /home/ppalucki/src/go/src/os/exec/exec.go:406 +0x4c4
  github.com/intelsdi-x/snap/control/plugin.(*ExecutablePlugin).WaitForExit()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:96 +0x4b
  github.com/intelsdi-x/snap/control/plugin.waitForKilledPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:342 +0x52

Previous read by goroutine 20:
  os.(*File).read()
      /home/ppalucki/src/go/src/os/file_unix.go:228 +0x57
  os.(*File).Read()
      /home/ppalucki/src/go/src/os/file.go:95 +0xbc
  bufio.(*Scanner).Scan()
      /home/ppalucki/src/go/src/bufio/scan.go:208 +0x823
  github.com/intelsdi-x/snap/control/plugin.logStdErr()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:325 +0x464

Goroutine 21 (running) created at:
  github.com/intelsdi-x/snap/control/plugin.waitHandling()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:195 +0x5c4
  github.com/intelsdi-x/snap/control/plugin.(*ExecutablePlugin).WaitForResponse()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:140 +0xbb
  github.com/intelsdi-x/snap/control.(*pluginManager).LoadPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin_manager.go:304 +0xe90
  github.com/intelsdi-x/snap/control.(*pluginControl).Load()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/control.go:286 +0x6b6
  github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1.TestLoad()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1/main_test.go:35 +0x7a
  testing.tRunner()
      /home/ppalucki/src/go/src/testing/testing.go:473 +0xdc

Goroutine 20 (finished) created at:
  github.com/intelsdi-x/snap/control/plugin.waitHandling()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:191 +0x477
  github.com/intelsdi-x/snap/control/plugin.(*ExecutablePlugin).WaitForResponse()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin/execution.go:140 +0xbb
  github.com/intelsdi-x/snap/control.(*pluginManager).LoadPlugin()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/plugin_manager.go:304 +0xe90
  github.com/intelsdi-x/snap/control.(*pluginControl).Load()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/control/control.go:286 +0x6b6
  github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1.TestLoad()
      /home/ppalucki/work/gopath15/src/github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1/main_test.go:35 +0x7a
  testing.tRunner()
      /home/ppalucki/src/go/src/testing/testing.go:473 +0xdc
==================
Found 2 data race(s)
exit status 66
FAIL    github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1        1.080s
```
- Expected

``` sh
PASS
ok      github.com/intelsdi-x/snap/plugin/collector/snap-collector-mock1        0.063s
```

**Comment by kjlyon** [comment] 2016-12-08 22:32
@ppalucki Is this still something you're interested in?

**Comment by kjlyon** [comment] 2016-12-12 20:15
Hi @ppalucki, I had @candysmurf look into this issue. She was not able to reproduce it from our latest Snap master on her ubuntu 14.04 vm. Small, medium and legacy tests passed with the race flag. Her test output is below: 

```vagrant@ubuntu1404:/share/src/github.com/intelsdi-x/snap/plugin/collector/snap-plugin-collector-mock1$ go run -race main.go {}
2016/12/09 18:40:36 method Decode reply type not a pointer: interface {}
2016/12/09 18:40:36 method Decrypt has wrong number of ins: 2
2016/12/09 18:40:36 method DecryptKey has wrong number of ins: 2
2016/12/09 18:40:36 method Encode has wrong number of ins: 2
2016/12/09 18:40:36 method Encrypt has wrong number of ins: 2
2016/12/09 18:40:36 method EncryptKey has wrong number of ins: 1
2016/12/09 18:40:36 method KillChan has wrong number of ins: 1
2016/12/09 18:40:36 method ListenAddress has wrong number of ins: 1
2016/12/09 18:40:36 method ListenPort has wrong number of ins: 1
2016/12/09 18:40:36 method Logger has wrong number of ins: 1
2016/12/09 18:40:36 method ResetHeartbeat has wrong number of ins: 1
2016/12/09 18:40:36 method SetEncrypter has wrong number of ins: 2
2016/12/09 18:40:36 method SetListenAddress has wrong number of ins: 2
2016/12/09 18:40:36 method Token has wrong number of ins: 1
{"Meta":{"Name":"mock","Version":1,"Type":0,"RPCType":0,"RPCVersion":0,"AcceptedContentTypes":["snap.gob"],"ReturnedContentTypes":["snap.gob"],"ConcurrencyCount":1,"Exclusive":false,"Unsecure":true,"CacheTTL":1100000000,"RoutingStrategy":0},"ListenAddress":"127.0.0.1:46232","PprofAddress":"","Token":"2Az-YobXF4nex1g7UDpCVPEevIOCanEGrAMgFhPLDOs=","Type":0,"State":0,"ErrorMessage":"","PublicKey":null}```

I'm going to close this issue and mark it as resolved. If you find this issue still exists, please reach out to us again or reopen this issue.

**Closed** 2016-12-12 20:18 UTC
Labels: tracked, type/bug
