### ISSUE TITLE
Regex in NewPluginMeta allows non-supported content-types

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap#765] opened 2016-03-15 02:51 UTC
The regex on lines 188 and 197 (https://github.com/intelsdi-x/snap/blob/master/control/plugin/plugin.go#L188) allow for a plugin to pass in any string with a period as an accepted content type even if it doesn't match the supported content-types defined here https://github.com/intelsdi-x/snap/blob/master/control/plugin/metric.go#L40-L46.

See http://play.golang.org/p/kcfI6Ep1t8

**Comment by danielscottt** [comment] 2016-05-25 21:57
Ping @mkleina && @geauxvirtual 

The `snap.` content types are the types that Snap _ships_ with.  This regex validation can be thought of similarly to AMQP bindings, and are meant to be open ended.  This is so a plugin author could use their own content types, effectively binding their plugins together.

**Comment by mkleina** [comment] 2016-05-27 08:41
So do you mean that this Pull Request is not really needed in the end? If so, maybe just close it.

**Comment by lynxbat** [comment] 2016-05-27 11:58
+1 on @danielscottt's comment. While we may use `.` in our built-in content types. It is irrelevant for a user. If we wish to build behavior around the types (i.e. searching, topical binding, etc) then we would need to implement a schema on top. 

So for now probably ok to close this as `not a bug` and close the PR.

**Comment by danielscottt** [comment] 2016-06-02 15:00
@mkleina yes. Will do.  Thanks for your consideration on this!

**Closed by danielscottt** 2016-06-02 15:00 UTC
Labels: bug, tracked
