### ISSUE TITLE
snapd enters bad state metrics cannot be found: task cannot be stopped or removed

### ISSUE THREAD

**Issue by nqn** [intelsdi-x/snap#952] opened 2016-05-25 22:05 UTC
```
 ./build/bin/snapctl task stop 314f7633-8d89-4cd5-b4bb-e656bd9b1c0c
Error stopping task:
error 0: Metric not found: /intel/foobar/mutilate/*/min error 1: Metric not found: /intel/foobar/mutilate/*/percentile/10th error 2: Metric not found: /intel/foobar/mutilate/*/percentile/5th error 3: Metric not found: /intel/foobar/mutilate/*/percentile/90th error 4: Metric not found: /intel/foobar/mutilate/*/percentile/95th error 5: Metric not found: /intel/foobar/mutilate/*/percentile/99th error 6: Metric not found: /intel/foobar/mutilate/*/std error 7: Metric not found: /intel/foobar/mutilate/*/avg 
(0a2acb7)⚡ [1] % ./build/bin/snapctl task remove 314f7633-8d89-4cd5-b4bb-e656bd9b1c0c                                                  ~/workspace/go/src/github.com/intelsdi-x/snap
Error stopping task:
Task must be stopped
```

**Comment by geauxvirtual** [comment] 2016-05-25 22:13
Can you provide the log output from snapd?

**Comment by mjbrender** [comment] 2016-07-19 18:55
This is an interesting bug. @nqn, could you reproduce it or tell us how you made it? Tagging as a bug until we find out more.

**Comment by bjray** [comment] 2016-07-26 16:51
I spoke with @nqn and he confirmed that we are unable to reproduce, so closing for now.

**Closed** 2016-07-26 16:52 UTC
Labels: tracked, type/bug
