### ISSUE TITLE
grpc based plugins create noise in snapteld's log when they are stopped

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap#1438] opened 2016-12-13 18:49 UTC
The call from snapteld stopping (killing) the plugin results in the following log message (from grpc) to be printed.

```
2016/12/13 10:36:50 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:55081: operation was canceled"; Reconnecting to {"127.0.0.1:55081" <nil>}
2016/12/13 10:36:50 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
```

To reproduce simply load any grpc based plugin.

**Comment by rashmigottipati** [comment] 2016-12-16 18:15
Reproduced the issue by running snap and loading apache collector and graphite publisher into the snap daemon using snaptel. 

Error Log - 
016/12/15 14:56:52 transport: http2Client.notifyError got notified that the client transport was broken EOF.
Plugin loaded
Name: apache
Version: 3
Type: collector
Signed: false
Loaded Time: Thu, 15 Dec 2016 14:56:52 PST

2016/12/15 14:56:52 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:51151: operation was canceled"; Reconnecting to {"127.0.0.1:51151" <nil>}
2016/12/15 14:56:52 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing

**Comment by katarzyna-z** [comment] 2017-03-01 15:05
Noisy logs come from grpc logger, see:
- `grpc: addrConn.resetTransport failed to create client transport...` - [https://github.com/grpc/grpc-go/blob/master/clientconn.go#L786](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L786)
- `grpc: addrConn.transportMonitor exits due to ...` - [https://github.com/grpc/grpc-go/blob/master/clientconn.go#L886](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L886)
- `transport: http2Client.notifyError got notified that the client transport was broken ...` - [https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L1126](https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L1126)

I don't think that we can do something with these logs. Do you have any ideas? Should we close this issue?

**Comment by IRCody** [comment] 2017-03-01 22:33
We can use [SetLogger](https://godoc.org/google.golang.org/grpc/grpclog#SetLogger) to set a logger for grpc -- either to make it match our log format or to ignore certain kinds of messages except when logs are set to debug.

**Comment by katarzyna-z** [comment] 2017-03-02 10:47
@IRCody Thanks, I'll try to use SetLogger.

**Closed** 2017-03-07 07:33 UTC
Labels: tracked, type/bug
