### ISSUE TITLE
TestWindowedSchedule in `windowed_schedule_test` is flaky.

### ISSUE THREAD

**Issue by ConnorDoyle** [intelsdi-x/snap#495] opened 2015-11-12 04:07 UTC
Link #341.

```
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=124.661902ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.649367664 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=99.25769ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.662037775 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=90.338552ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.683691908 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=77.629259ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.696392913 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=64.97525ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.709055567 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=39.584934ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.721744341 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=31.712522ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.742318438 -0800 PST 
...time="2015-11-11T20:05:01-08:00" level=debug msg="Waiting for window to start" _block=windowed-wait _module=schedule sleep-duration=49.976754ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="Last was unset using start time" _block=windowed-wait _module=schedule 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.829301094 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.84010256 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.852787427 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.865474491 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.87816683 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.888267105 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.89927764 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.910484 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.921692124 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.932898714 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.944103504 -0800 PST 
..time="2015-11-11T20:05:01-08:00" level=debug msg="Last was unset using start time" _block=windowed-wait _module=schedule 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=249.929109ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.95574383 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=239.711194ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.965960004 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=228.490375ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.97718043 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=218.112143ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.987551807 -0800 PST 
time="2015-11-11T20:05:01-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=206.906202ms 
time="2015-11-11T20:05:01-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:01.998765957 -0800 PST 
time="2015-11-11T20:05:02-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=195.688302ms 
time="2015-11-11T20:05:02-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:02.009975357 -0800 PST 
time="2015-11-11T20:05:02-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=184.483235ms 
time="2015-11-11T20:05:02-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:02.02118561 -0800 PST 
time="2015-11-11T20:05:02-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=173.271293ms 
time="2015-11-11T20:05:02-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:02.032400965 -0800 PST 
time="2015-11-11T20:05:02-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=162.05743ms 
time="2015-11-11T20:05:02-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:02.043611771 -0800 PST 
time="2015-11-11T20:05:02-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=151.78024ms 
time="2015-11-11T20:05:02-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:02.053886867 -0800 PST 
time="2015-11-11T20:05:02-08:00" level=debug msg="Within window, calling interval" _block=windowed-wait _module=schedule time-before-stop=140.575803ms 
time="2015-11-11T20:05:02-08:00" level=debug msg="waiting for interval" _block=windowed-wait _module=schedule interval=10ms last=2015-11-11 20:05:02.065096318 -0800 PST 
....
Failures:

  * /Users/cpdoyle/hack/go/src/github.com/intelsdi-x/pulse/pkg/schedule/windowed_schedule_test.go 
  Line 52:
  Expected '14' to be between '15' and '17' or equal to one of them (but it wasn't)!


19 total assertions

--- FAIL: TestWindowedSchedule (0.71s)
FAIL
coverage: 91.1% of statements
FAIL    github.com/intelsdi-x/pulse/pkg/schedule        1.217s
make: *** [test] Error 1
```

**Comment by IRCody** [comment] 2016-08-18 19:43
@ConnorDoyle, I'm closing this since the issue is fairly old and I don't recall seeing this test fail either locally, or in travis in the past few months. So it's either extremely flaky or has been fixed. If this issue is reported/seen again we can reopen this issue.

**Closed by IRCody** 2016-08-18 19:43 UTC
Labels: tracked, type/bug
