### ISSUE TITLE
go get github.com/intelsdi-x/snap does not work

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap#994] opened 2016-06-15 15:48 UTC
It looks like `go get github.com/intelsdi-x/snap` fails with the following error:

```
# github.com/intelsdi-x/snap/grpc/controlproxy/rpc
.gvm/pkgsets/go1.6/global/src/github.com/intelsdi-x/snap/grpc/controlproxy/rpc/control.pb.go:380: undefined: grpc.SupportPackageIsVersion2
```

**Comment by IRCody** [comment] 2016-06-15 17:07
This seems like it's erroring when go get is running a build. I believe you probably have to run make to ensure the correct grpc version of the library is loaded via godeps before a a build will succeed.

What is the state of the repository after you get this error? Are you able to run make successfully?

**Comment by elemoine** [comment] 2016-06-16 08:40
First of all, note that the [BUILD_AND_TEST doc](https://github.com/intelsdi-x/snap/blob/master/docs/BUILD_AND_TEST.md#getting-started) indicates that `go get github.com/intelsdi-x/snap` is to be used to get Snap.

Now, to answer, your questions: after I run `go get github.ccom/intelsdi-x/snap` I can indeed changedir to the `snap` directory and run `make`. That works.

But shouldn't `go get github.com/intelsdi-x/snap` just complete without errors? Or should the doc be changed?

**Comment by IRCody** [comment] 2016-06-16 14:51
So the issue seems to be that there is a library (grpc in this case) that has a breaking change between the version we are linked against and the version on master. This error could happen with any library that we use so we should probably address it in a general way. Maybe the docs should be changed to say `go get -d github.com/intelsdi-x/snap` so that the go tool will not attempt to build/install but instead download only?

**Comment by elemoine** [comment] 2016-06-16 15:58
Yes, I tested `go get -d` and it works. I just don't know if people expect `go get github.com/intelsdi-x/snap` to work. Maybe they would expect it to work if they build a package that depends on snap and that itself can be installed using `go get`. I don't know. Maybe it's time to learn about the "vendor" thing and use it in Snap.

**Comment by IRCody** [comment] 2016-06-16 17:13
Vendoring would help if we checked in all dependencies. I'm not sure what another answer is unless we just agree to stay on master for all of our dependencies. Is there another answer you can think of?

The docs should be updated to add the `-d` flag.

**Comment by elemoine** [comment] 2016-06-17 07:49
I guess this discussion is related to https://github.com/intelsdi-x/snap/pull/932 and https://github.com/intelsdi-x/snap/pull/933 (which were closed with no written conclusions).

In the mean time I agree that the docs should be updated to use the `-d` flag.

**Comment by elemoine** [comment] 2016-06-19 21:19
@IRCody, FYI I've been experimenting with migrating Snap to `vendor/` and removing `Godeps` entirely. See my [vendor branch](https://github.com/intelsdi-x/snap/compare/master...elemoine:vendor).

So this branch adds a `vendor` directory with Git submodules for all the Snap dependencies. My final goal is to see if we can use the standard `go get` command to download, build and install Snap, while still being able to use fixed dependency versions.

This is what I've used for testing:

```
$ export GOPATH=/tmp/go
$ mkdir -p $GOPATH/src/github.com/intelsdi-x
$ cd $GOPATH/src/github.com/intelsdi-x
$ git clone -b vendor --single-branch https://github.com/elemoine/snap
$ cd snap
$ git submodule update --init --recursive
$ go install  # make all works as well
```

This should more or less mimic what `go get` does. I'd like to be able to test `go get github.com/intelsdi-x/snap`, but I don't know how to do it (given that my changes are in a specific Git repo and branch).

This is just for experimenting at this point, but I am happy to create a PR to Snap for discussion if there's interest.

**Comment by IRCody** [comment] 2016-06-20 17:55
@elemoine: The way you are testing it it is the best way I can think of also. Are you adding the vendor'ed dependencies by hand?

**Comment by nanliu** [comment] 2016-06-20 18:46
The long version of the comment left in #933, we explored a variety of go dependency tools and unfortunately they all have shortcomings, whether it's repo bloat, incompatible with go get, hard to track and update dependencies (especially considering all the plugins). We are trying to make a decision focused on reproducibility, but keeping in mind development v.s. release needs as well as an easy way to update all snap plugin go dependencies. So far we haven't found a good compromise yet. If you have a working branch, please feel free to submit a PR and we will be happy to evaluate it for consideration.

**Comment by elemoine** [comment] 2016-06-21 06:40
@nanliu Thanks for your comment. I created https://github.com/intelsdi-x/snap/pull/1008 for discussion.

**Closed** 2016-06-21 22:00 UTC
Labels: documentation
