### ISSUE TITLE
Snap doesn't clean tmp folder after stopping when using `auto_discover_path` feature.

### ISSUE THREAD

**Issue by mkuculyma** [intelsdi-x/snap#1580] opened 2017-04-03 10:12 UTC
**Snap daemon version**: 1.2.0
**Environment**:
- **OS**: Ubuntu 16.04
- **Kernel**: 4.4.0-62-generic

**Problem**:
When using `auto_discover_path` feature there are snap-plugin-xxxxxx directories with plugins' binaries being created in the /tmp folder. After killing snapteld the directories are **not removed**. Each restart of Snap daemon causes creation of additional snap-plugin-xxxxxx directories.

**Steps to reproduce**:
1. Download plugin binaries to directory `/opt/snap/autoload` (i.e. disk, ethtool, perfevents, influxdb, cpu)
2. Start Snap with option `auto_discover_path` set to `/opt/snap/autoload`
3. Kill snapteld and start again several times. 
4. Observe numerous snap-plugin-xxxxxx directories being create in /tmp/ folder.

**Comment by rashmigottipati** [comment] 2017-04-13 22:54
@mkuculyma Thanks for opening this issue. However, I wasn't able to reproduce the same using the -a option. I noticed that the files were created when I started snap using snapteld -a "/opt/snap/plugins" -t 0 -l 1, but were destroyed after killing snapteld.

**Comment by rashmigottipati** [comment] 2017-04-13 23:01
When you start snapteld with the -a option or otherwise, you notice the temp location the binary is being copied to. It's a debug message that looks like this :
wrote 6992128 to /var/folders/jn/zs1t3pfx3234qlf5d6lxvnl00000gp/T/snap-plugin-105158287/snap-plugin-publisher-mock-file-grpc

After killing snapteld, you can notice that when you try to open snap-plugin-105158287, it doesn't exist anymore. Can you confirm the same?

**Comment by rashmigottipati** [comment] 2017-04-17 23:11
Closing this issue as it's not reproducible anymore. Tried with/without the auto_discover_path option and didn't see this behavior. I noticed that snap cleans up the tmp folders in both cases. 

@mkuculyma please try it out again and let me know if you still see any issues. To be able to differentiate easily, I would suggest you to remove all the existing tmp files and try out the steps to reproduce that you listed earlier. I would look at the debug messages of snap to verify the unique number associated with each plugin load and try to open the same file after killing snapteld. It shouldn't exist anymore. Let me know if otherwise. Thanks!

**Closed by rashmigottipati** 2017-04-17 23:11 UTC
Labels: tracked, type/bug
