### ISSUE TITLE
Problem with Libvirt plugin for memory related metrics

### ISSUE THREAD

**Issue by diziup** [intelsdi-x/snap#1402] opened 2016-12-01 07:55 UTC
Hello,
We are collecting some libvirt metrics on a host with 3 virtual machines configured in it,
and some of the memory related metrics are constantly 0.
For instance:
/mem/unused
/mem/swap_out
/mem/swap_in
/mem/nr
/mem/min_fault
/mem/major_fault
/mem/available

We used stress command to add load to a specific VM, and these metrics remained unchanged (value of constant 0).
I would add that the corresponding metrics of the host conditions from the meminfo plugin did show a change in the metrics.

What could be the reason for this?
Thank you.

**Comment by katarzyna-z** [comment] 2016-12-01 08:18
Could you check if you use the latest version of the plugin? The plugin version should be 10, you can check this with following command `snaptel plugin list`.
Please see [this issue](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/38), it seems that we should reopen it.

**Comment by diziup** [comment] 2016-12-01 08:26
It is indeed not updated,
we are using 0.18  version of snap,
do you happen to know if we can update only the libvirt plugin to version 10 without updating to the latest version of snap (1.0.0)?
Thanks

**Comment by katarzyna-z** [comment] 2016-12-01 08:39
I think that you can update only libvirt plugin. It seems that the issue is not connected with Snap's version.

**Comment by sandlbn** [comment] 2016-12-01 09:09
@diziup memory metrics are dependent on hypervisor version, not all hypervisors are exposing same amount of metrics, most of the listed by you are not exposed by kvm. This is also related to the https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/38 . Are you using kvm or xen ? I reopened issue against libvirt and I will would like to track activity there.

**Comment by diziup** [comment] 2016-12-01 14:52
We are using kvm, and we have configured the missing metrics  (memory/available etc) to be collected.
We have updated the plugin version 10,
we have still not managed to get via snap plugin the metrics, we are working on it.
yet we are encountering  now a different problem with the  new plugin version -
in the former version we have used the option "snapctl metric list" to get all the possible VM's and their interfaces, and it worked fine.
Now, with the new plugin version, we noticed that only a single interface per VM is fetched by this option, 
that is, if we have 3 VM's and each has 3 interfaces configured, 
now it will fetch only a single interface per VM.
Can this be fixed?

**Comment by sandlbn** [comment] 2016-12-01 15:11
@diziup Can we move discussion to the https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/43  ? I create ticket for you. I created patch but I will be happy if you can test it on your system.

**Comment by sandlbn** [comment] 2016-12-01 15:23
@diziup Here is a new version of plugin. if you can test it on your system will be really cool. 

https://drive.google.com/file/d/0B0iNIa564eX0d2VoTlptSVBMRVU/view?usp=sharing

**Comment by kindermoumoute** [comment] 2016-12-01 17:10
Alright, I close the issue as the conversation moved to https://github.com/intelsdi-x/snap-plugin-collector-libvirt/issues/43

**Closed by kindermoumoute** 2016-12-01 17:10 UTC
