### ISSUE TITLE
Seed node does not join the cluster after restart

### ISSUE THREAD

**Issue by ralberto** [intelsdi-x/snap#1283] opened 2016-10-14 10:52 UTC
A cluster of 3 nodes was started using the tribe configuration below:

```
tribe:
  enable: true
  bind_addr: 0.0.0.0
  bind_port: 6000
  seed: 10.112.226.139
```

Executing `snapctl member list` shows all three nodes. However if we restart seed node, it does not join the cluster again. Other nodes join the cluster without any problem!

**Comment by IRCody** [comment] 2016-10-14 17:21
Can you go into more detail about how you're restarting the seed node, including what command you're using?

**Comment by jcooklin** [comment] 2016-10-15 17:58
@ralberto in this example the first node needs to (re)start with a seed referring to **any** other node in the original cluster else it will start and essentially create a new cluster that includes only itself.

**Comment by ralberto** [comment] 2016-10-17 09:55
Thanks. 
Why it's not possible to specify a list of seed nodes? Being able to specify only one seed node we have a single point of failure.

**Comment by jcooklin** [comment] 2016-10-18 19:22
> Why it's not possible to specify a list of seed nodes?  

There's no technical reason that we couldn't enable a providing multiple seeds at startup.  I've added   https://github.com/intelsdi-x/snap/issues/1297 to capture the request.

**Comment by mjbrender** [comment] 2016-12-09 18:37
@ralberto just pinged you on #1297 because this issue is expected behavior as of right now. I'm going to close this issue and we can keep track of changes to tribe on the new issue. Thanks for the suggestion Rui!

**Closed by mjbrender** 2016-12-09 18:37 UTC
Labels: tracked, type/bug
